const DICTIONARY = {

    en: {
        PLAY_AGAIN_QUESTION: "Play again (YES/no)? ",
        PLAYER_1: "one",
        PLAYER_2: "two",
        MENU: "menu",
        PLAY_GAME: "1. Play game" ,
        GAME_MODE_PREFERED: "What gamemode do you want to play?",
        GAME_MODE_PVP: "1. PvP (Player vs Player)",
        GAME_MODE_PVC: "2. PVC (Player vs Computer)",
        SETTINGS: "2. Settings",
        PREFERED_LANGUAGE: "Choose your prefered language",
        ENGLISH: "1. English",
        NORWEGIAN: "2. Norwegian",
        EXIT_GAME: "3. Exit game",
        PLACE_MARK: "Place your mark at: ",
        PLAYER: "Player ",
        YOUR_TURN: " it is your turn",
        WINNER: "Winner is player ",
        DRAW: "It's a draw!",
        GAME_OVER: "GAME OVER",
        CONFIRM: "y",
    },
    no: {
        PLAY_AGAIN_QUESTION: "Spille en gang til (Ja/nei)? ",
        PLAYER_1: "en",
        PLAYER_2: "to",
        MENU: "meny",
        PLAY_GAME: "1. Start spill" ,
        GAME_MODE_PREFERED: "Hvilken spillmodus vil du spille?",
        GAME_MODE_PVP: "1. PVP (Spiller mot Spiller)",
        GAME_MODE_PVC: "2. PVC (Spiller mot Datamaskin)",
        SETTINGS: "2. Instillinger",
        PREFERED_LANGUAGE: "Velg språk",
        ENGLISH: "1. Engelsk",
        NORWEGIAN: "2. Norsk",
        EXIT_GAME: "3. Slutt spill",
        PLACE_MARK: "Plasser ditt symbol: ",
        PLAYER: "Spiller ",
        YOUR_TURN: " det er din tur",
        WINNER: "Vinneren er spiller ",
        DRAW: "Det ble uavgjort!",
        GAME_OVER: "SLUTT",
        CONFIRM: "j",
    }
}

export default DICTIONARY;